services:
  db:
    container_name: "ProjectDB"
    image: postgres:alpine
    volumes:
      - "./.database/postgres-data:/var/lib/postgresql:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: unless-stopped
